### ISSUE TITLE
Any way i can go around this error? 

### ISSUE THREAD

**Issue by maxozo** [broadinstitute/tensorqtl#144]
This causes thensorqtl to fail. I have 4 phenotypes, all 4 are dropped as there are no variants in the region that are passing the thresholds predefined. As all of thme are dropped there is nothing left to test and the thread gets stuck.

```
cis-QTL mapping: nominal associations for all variant-phenotype pairs
  * 1033 samples
  * 4 phenotypes
  * 6 covariates
  * 6100111 variants
  * cis-window: ±1,000,000

  * checking phenotypes: 4/4
    ** dropping 4 phenotypes without variants in cis-window
  * Computing associations
    Mapping chromosome 21
Exception in thread Thread-7:
Traceback (most recent call last):
  File "/home/container_user/conda/lib/python3.9/threading.py", line 980, in _bootstrap_inner
    self.run()
  File "/home/container_user/conda/lib/python3.9/site-packages/tensorqtl/genotypeio.py", line 50, in run
    for item in self.generator:
  File "/home/container_user/conda/lib/python3.9/site-packages/tensorqtl/genotypeio.py", line 489, in generate_data
    chr_offset = offset_dict[chrom]
KeyError: '21'
```

**Comment by maxozo** [comment]
I resolved it by doing this as per my pull request. https://github.com/broadinstitute/tensorqtl/compare/master...maxozo:tensorqtl:patch-1 
Untill this is merged i have made a copy of genotypeio.py with a patch and i load it from my local files instead of tensorqtl package.

**Comment by francois-a** [comment]
e97f4ea903b47b139a47de6e9d2e3bf140e49d6f should fix this.

**Comment by pschreiner** [comment]
> [e97f4ea](https://github.com/broadinstitute/tensorqtl/commit/e97f4ea903b47b139a47de6e9d2e3bf140e49d6f) should fix this.

I still get the indicated error even when using the updated (e97f4ea) container

**Comment by francois-a** [comment]
Can you provide more details and/or a reproducible example?

**Comment by pschreiner** [comment]
I had the same error as maxozo above. I used maxozo's (7559a29) container and can confirm that it fixed the issue of pushing to the next iteration if phenotypes are provided with no variants in the cis window.
